export default {
  Login: 'تسجيل دخول',
  'Sign In': 'تسجيل دخول',
  'Sign Up': 'إنشاء حساب',
  Register: 'إنشاء حساب',
  'Phone Number / Email Address': 'رقم الهاتف / الايميل',
  'Enter Email / Mobile Number': 'قم بإدخال رقم الهاتف / الايمايل',
  'Forgot Password': 'نسيت كلمة المرور',
  'To Complete Your Registeration': 'و سنقوم بارسال رمز لاتمام عملية التسجيل',
  "And We'll Send You The Instructions": 'و سوف نرسل اليك التعليمات',
  'Forgot Password?': 'نسيت كلمة المرور ؟',
  'Your Identity Has Been Verified': 'لقد تم تأكيد هويتك',
  Profile: 'حسابي',
  Notifications: 'الاشعارات',
  'Or Sign In With': 'أو سجل دخول عن طريق',
  'Skip >>': 'تخطي >>',
  "Don't Have An Account ?": 'ليس لدي حساب !',
  Save: 'حفظ',
  Logout: 'تسجل الخروج',
  Home: 'الرئيسية',
  password: 'كلمة المرور',
  Password: 'كلمة المرور',
  Phone: 'رقم الهاتف',
  Update: 'تغيير',
  Email: 'البريد الإلكتروني',
  Congratulations: 'تهانينا',
  'Set Your New Password': 'من فضلك ادخل كلمة المرور الجديده',
  'Your Password Has Been Updated': 'لقد تم تغيير كلمة المرور بنجاح',
  'Email Address': 'البريد الإلكتروني',
  'New Password': 'كلمة المرور الجديده',
  'Confirm New Password': 'تأكيد كلمة المرور',
  'Or Register With': 'أو سجل دخول عن طريق',
  'First name': 'الاسم الاول',
  'Full Name': 'الأسم بالكامل',
  'Last name': 'الاسم الاخير',
  Send: 'إرسال',
  Favoriets: 'المفضلة',
  Voucher: 'الكوبونات',
  'My Orders': 'طلباتي',
  Offers: 'عروض',
  Settings: 'الضبط',
  Suport: 'فريق الدعم',
  Apply: 'أضف',
  'Add Voucher': 'اضف كوبون الخصم',
  'Deliver To': 'التوصيل الى',
  'What You Are Looking For ?': 'ما الذي تبحث عنه؟',
  'Explore Category': 'إستعرض الفئات',
  'View All': 'إستعرض الكل',
  'Please enter a valid mobile number': 'الرجاء إدخال رقم جوال صحيح',
  'Already Registered?': 'لدي حساب بالفعل!',
  'Enter the 6-digit code sent to number':
    'قم بأدخال ال 6 ارقام التي تم ارسالها علي رقم',
  'Log In': 'تسجيل دخول',
  'Current Location': 'الموقع الحالي',
  'Verify And Proceed': 'تأكيد',
  Favorite: 'المفضله',
  Supermarket: 'سوبر ماركت',
  Beef: 'لحوم',
  Chicken: 'دواجن',
  Fish: 'أسماك',
  Fruit: 'فواكه',
  Vegetables: 'خضراوات',
  'You Can Get Our Offer': 'يمكنك الاستفاده من الخصومات',
  'Green Apple': 'تفاح اخضر',
  'Refresh Market': 'ريفريش ماركت',
  'Smile Market': 'ريفريش ماركت',
  'Restaurant Market': 'ريفريش ماركت',
  ' Min': ' دقيقه',
  'EX . 22 January 2022': 'تاريخ الانتهاء 22',
  Balance: ' الرصيد',
  'Today 03 January 2021': 'اليوم   22يناير 2021',
  'Voucher 12457': 'قسيمة رقم 12457',
  'With 10% From Total Purchases ': 'في فاتورة مشتريات #12457  22 يناير 2021',
  Expired: 'منتهيه',
  'Shopping Cart': 'سلة المشتريات',
  'Order Details': 'تفاصيل الطلب',
  Address: 'العنوان',
  Checkout: 'الدفع',
  '500 ml': '500 ملل',
  'Cart Total': 'اجمالي السله',
  'Services Charge': 'خدمه',
  Discount: 'خصم',
  Next: 'التالي',
  'Total Amount': 'الأجمالي',
  'Add More Items': 'إضافة المزيد',
  'Enter Promo Code': 'اضف كوبون الخصم',
  'KitKat Ruby Cocoa Beans': 'شيكولاته كيت كات',
  House: 'المنزل',
  Office: 'المكتب',
  Club: 'النادي',
  'Mobile Number': 'رقم الموبايل',
  'Add A New One +': 'إضافة عنوان جديد +',
  'Cash By Deliver': 'الدفع كاش عند الاستلام',
  'Online Payment': 'الدفع اونلاين',
  'Check Out': 'دفع',
  Cancel: 'إلغاء',
  'My Cards': 'الكروت',
  Addresses: 'العناوين',
  'Check Out  >': 'إستعراض >',
  Language: 'اللغه',
  'Get OTP': 'إرسال الرمز',
  'Enter Mobile Number': 'قم بإدخال رقم الهاتف',
  'My Addresses': 'العنوان',
  Notification: 'الاشعارات',
  'Birth Date': 'تاريخ الميلاد',
  'Log Out': 'تسجيل خروج',
  'Banana Item Is unfortunately Out Of Stock And We Suggest You Another Items Please Check It':
    'للأسف لقد نفذ طلبك ( الموز ) لدينا و لكن نقترح عليك منتج اخر ك بديل ألقي عليه نظره',
  'Fresh Market Order 1247': 'فريش ماركت طلب 12478 اليوم 2:30',
  'Miami st.12 - Building 20 , Alexandria , Egypt':
    'ميامي شارع 12 - عمارة رقم 20 , الاسكندريه , مصر',
  'Mobile Nember': 'رقم الهاتف',
  'Your Identity Has Been Verified': 'تم التحقق من هويتك',
  'Set Your New Password': 'اضبط كلمة المرور الجديدة',
  'Confirm New Password': 'تأكيد كلمة المرور الجديدة',
};
